import os
import random
from PIL import Image, ImageDraw, ImageFont, ImageFilter

OUTPUT_DIR = "test_slips"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Font loader with Fedora system fallbacks
def get_fonts():
    fedora_font_paths = [
        "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf",
        "/usr/share/fonts/google-noto/NotoSans-Regular.ttf",
        "/usr/share/fonts/liberation-sans/LiberationSans-Regular.ttf"
    ]
    font_path = next((p for p in fedora_font_paths if os.path.exists(p)), None)
    
    if font_path:
        return {
            "title": ImageFont.truetype(font_path, 22),
            "amount": ImageFont.truetype(font_path, 30),
            "body": ImageFont.truetype(font_path, 16),
            "small": ImageFont.truetype(font_path, 12),
        }
    default = ImageFont.load_default()
    return {"title": default, "amount": default, "body": default, "small": default}

FONTS = get_fonts()

def render_slip(
    bank_name="Commercial Bank",
    amount_str="Rs. 25,000.00",
    ref_no="839201",
    to_acc="XXXX1234",
    from_name="Kajaram G.",
    date_str="2026-09-29 10:15:30",
    status="TRANSFER SUCCESSFUL",
    status_color=(34, 139, 34),
    tamper_patch=None
):
    """Draws a clean standard mobile banking receipt card."""
    width, height = 480, 640
    img = Image.new("RGB", (width, height), color=(245, 247, 250))
    draw = ImageDraw.Draw(img)

    # Card background
    draw.rectangle([20, 20, width - 20, height - 20], fill=(255, 255, 255), outline=(220, 225, 230), width=2)
    
    # Header Banner
    draw.rectangle([20, 20, width - 20, 90], fill=(24, 43, 73))
    draw.text((40, 42), bank_name.upper(), fill=(255, 255, 255), font=FONTS["title"])

    # Status & Amount
    draw.text((40, 115), status, fill=status_color, font=FONTS["body"])
    draw.text((40, 145), amount_str, fill=(20, 20, 20), font=FONTS["amount"])

    draw.line([(40, 195), (width - 40, 195)], fill=(230, 230, 230), width=1)

    # Metadata Rows
    rows = [
        ("Reference Number:", ref_no),
        ("To Account:", to_acc),
        ("Recipient:", "BuildStart Business Store"),
        ("Sender:", from_name),
        ("Date & Time:", date_str),
        ("Payment Channel:", "Mobile Banking App")
    ]

    y = 220
    for label, val in rows:
        draw.text((40, y), label, fill=(110, 115, 125), font=FONTS["body"])
        draw.text((210, y), str(val), fill=(30, 30, 30), font=FONTS["body"])
        y += 42

    # Footer note
    draw.text((40, height - 60), "Official e-receipt generated by bank portal.", fill=(160, 160, 160), font=FONTS["small"])

    # Tamper simulation (digital patch over amount)
    if tamper_patch:
        # Draw mismatched white rectangle over amount and print poorly aligned digits
        draw.rectangle([35, 140, 320, 185], fill=(255, 255, 255))
        draw.text((38, 142), tamper_patch, fill=(200, 0, 0), font=FONTS["title"])

    return img

# =====================================================================
# TEST CASE GENERATION
# =====================================================================

print("Generating synthetic test payment slips...")

# 1. Normal Valid Payment (Matches expected Rs 25,000, A/C XXXX1234, Ref 839201)
render_slip(
    amount_str="Rs. 25,000.00",
    ref_no="839201",
    to_acc="XXXX1234",
    status="TRANSFER SUCCESSFUL"
).save(f"{OUTPUT_DIR}/01_normal_valid.png")

# 2. Wrong Amount (Underpaid Rs 15,000 instead of 25,000)
render_slip(
    amount_str="Rs. 15,000.00",
    ref_no="839202",
    to_acc="XXXX1234"
).save(f"{OUTPUT_DIR}/02_wrong_amount.png")

# 3. Wrong Account (Paid to personal account instead of business)
render_slip(
    amount_str="Rs. 25,000.00",
    ref_no="839203",
    to_acc="YYYY9999"
).save(f"{OUTPUT_DIR}/03_wrong_account.png")

# 4. Old Payment (Genuine transaction, but months old)
render_slip(
    amount_str="Rs. 25,000.00",
    ref_no="839204",
    to_acc="XXXX1234",
    date_str="2024-03-12 14:02:11"
).save(f"{OUTPUT_DIR}/04_old_payment.png")

# 5. Digitally Edited / Manipulated Slip (Tampered Amount text)
render_slip(
    ref_no="839205",
    to_acc="XXXX1234",
    tamper_patch="Rs. 25,000.00"
).save(f"{OUTPUT_DIR}/05_manipulated_slip.png")

# 6. Unclear / Blurry Slip (Camera motion or low resolution)
unclear_img = render_slip(amount_str="Rs. 25,000.00", ref_no="839206")
unclear_img = unclear_img.filter(ImageFilter.GaussianBlur(radius=8))
unclear_img.save(f"{OUTPUT_DIR}/06_unclear_blurry.png")

# 7. Cropped / Cut Off Slip (Missing critical bottom reference/account details)
cut_img = render_slip(amount_str="Rs. 25,000.00", ref_no="839207")
cut_img = cut_img.crop((0, 0, 480, 220))  # Only header and amount visible
cut_img.save(f"{OUTPUT_DIR}/07_cropped_cutoff.png")

# 8. Same Payment, Different Presentation (Cropped + rotated version of #1 to test pHash)
same_pay = render_slip(amount_str="Rs. 25,000.00", ref_no="839201")
same_pay = same_pay.rotate(2, expand=True, fillcolor=(240, 240, 240))
same_pay = same_pay.crop((10, 10, 460, 620))
same_pay.save(f"{OUTPUT_DIR}/08_same_payment_different_crop.png")

# 9. Failed Bank Transfer (Slip indicates transaction cancelled/rejected by bank)
render_slip(
    amount_str="Rs. 25,000.00",
    ref_no="839209",
    status="TRANSACTION FAILED: INSUFFICIENT BALANCE",
    status_color=(200, 30, 30)
).save(f"{OUTPUT_DIR}/09_failed_status.png")

# 10. Missing Evidence / Non-Payment Upload (User uploaded a selfie or document)
unrelated_img = Image.new("RGB", (480, 480), color=(100, 149, 237))
d = ImageDraw.Draw(unrelated_img)
d.text((120, 220), "PHOTO OF A CAT / LANDSCAPE", fill=(255, 255, 255), font=FONTS["body"])
unrelated_img.save(f"{OUTPUT_DIR}/10_unrelated_file.png")

# 11. Conflicting Evidence (Amount matches, but reference does not match any bank SMS)
render_slip(
    amount_str="Rs. 25,000.00",
    ref_no="000111",
    to_acc="XXXX1234"
).save(f"{OUTPUT_DIR}/11_conflicting_no_sms.png")

print(f"Generated 11 test slip images inside the '{OUTPUT_DIR}/' directory.")